# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'leafi_qt_ui/leafi_mainwindow_WOXpaper.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LeafInterrogatorMainWindow(object):
    def setupUi(self, LeafInterrogatorMainWindow):
        LeafInterrogatorMainWindow.setObjectName("LeafInterrogatorMainWindow")
        LeafInterrogatorMainWindow.resize(947, 743)
        LeafInterrogatorMainWindow.setMinimumSize(QtCore.QSize(400, 0))
        self.centralWidget = QtWidgets.QWidget(LeafInterrogatorMainWindow)
        self.centralWidget.setMinimumSize(QtCore.QSize(800, 400))
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.main_tabs = QtWidgets.QTabWidget(self.centralWidget)
        self.main_tabs.setMinimumSize(QtCore.QSize(0, 0))
        self.main_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main_tabs.setObjectName("main_tabs")
        self.tab_detect_contour = QtWidgets.QWidget()
        self.tab_detect_contour.setObjectName("tab_detect_contour")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_detect_contour)
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.splitter_6 = QtWidgets.QSplitter(self.tab_detect_contour)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.widget_3 = QtWidgets.QWidget(self.splitter_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_3 = QtWidgets.QSplitter(self.widget_3)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self._image_opengl_widget = ImageOpenGLWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._image_opengl_widget.sizePolicy().hasHeightForWidth())
        self._image_opengl_widget.setSizePolicy(sizePolicy)
        self._image_opengl_widget.setMinimumSize(QtCore.QSize(0, 0))
        self._image_opengl_widget.setMouseTracking(False)
        self._image_opengl_widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self._image_opengl_widget.setAcceptDrops(True)
        self._image_opengl_widget.setObjectName("_image_opengl_widget")
        self.widget_2 = QtWidgets.QWidget(self.splitter_3)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.previous_image_btn = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_image_btn.sizePolicy().hasHeightForWidth())
        self.previous_image_btn.setSizePolicy(sizePolicy)
        self.previous_image_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.previous_image_btn.setAcceptDrops(True)
        self.previous_image_btn.setObjectName("previous_image_btn")
        self.horizontalLayout_7.addWidget(self.previous_image_btn)
        self.widget_13 = QtWidgets.QWidget(self.widget_2)
        self.widget_13.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self._image_counter_lineEdit = QtWidgets.QLineEdit(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._image_counter_lineEdit.sizePolicy().hasHeightForWidth())
        self._image_counter_lineEdit.setSizePolicy(sizePolicy)
        self._image_counter_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self._image_counter_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self._image_counter_lineEdit.setAcceptDrops(False)
        self._image_counter_lineEdit.setInputMask("")
        self._image_counter_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self._image_counter_lineEdit.setObjectName("_image_counter_lineEdit")
        self.horizontalLayout_5.addWidget(self._image_counter_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.widget_13)
        self.label_5.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.image_counter_label = QtWidgets.QLabel(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_counter_label.sizePolicy().hasHeightForWidth())
        self.image_counter_label.setSizePolicy(sizePolicy)
        self.image_counter_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.image_counter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_counter_label.setObjectName("image_counter_label")
        self.horizontalLayout_5.addWidget(self.image_counter_label)
        self.horizontalLayout_7.addWidget(self.widget_13)
        self.next_image_btn = QtWidgets.QPushButton(self.widget_2)
        self.next_image_btn.setObjectName("next_image_btn")
        self.horizontalLayout_7.addWidget(self.next_image_btn)
        self._contour_opengl_widget = ContourOpenGLWidget(self.splitter_3)
        self._contour_opengl_widget.setMinimumSize(QtCore.QSize(0, 0))
        self._contour_opengl_widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self._contour_opengl_widget.setObjectName("_contour_opengl_widget")
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.widget_4 = QtWidgets.QWidget(self.splitter_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(150, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_5 = QtWidgets.QSplitter(self.widget_4)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self._contour_leaflet_tab = QtWidgets.QTabWidget(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._contour_leaflet_tab.sizePolicy().hasHeightForWidth())
        self._contour_leaflet_tab.setSizePolicy(sizePolicy)
        self._contour_leaflet_tab.setObjectName("_contour_leaflet_tab")
        self.contour = QtWidgets.QWidget()
        self.contour.setObjectName("contour")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.contour)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox = QtWidgets.QGroupBox(self.contour)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 180))
        self.groupBox.setStyleSheet("QGroupBox {\n"
" border: 1px solid gray;\n"
"border-radius: 9px;\n"
"margin-top: 0.5em;\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"left: 10px;\n"
"padding: 0 3px 0 3px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(11, 11, 11, 1)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.threshhold_lbl = QtWidgets.QLabel(self.groupBox)
        self.threshhold_lbl.setObjectName("threshhold_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.threshhold_lbl)
        self._threshold = QtWidgets.QLineEdit(self.groupBox)
        self._threshold.setMinimumSize(QtCore.QSize(50, 0))
        self._threshold.setMaximumSize(QtCore.QSize(200, 16777215))
        self._threshold.setFocusPolicy(QtCore.Qt.ClickFocus)
        self._threshold.setObjectName("_threshold")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self._threshold)
        self.min_perimeter_lbl = QtWidgets.QLabel(self.groupBox)
        self.min_perimeter_lbl.setObjectName("min_perimeter_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.min_perimeter_lbl)
        self._min_perimeter = QtWidgets.QLineEdit(self.groupBox)
        self._min_perimeter.setMinimumSize(QtCore.QSize(50, 0))
        self._min_perimeter.setMaximumSize(QtCore.QSize(200, 16777215))
        self._min_perimeter.setFocusPolicy(QtCore.Qt.ClickFocus)
        self._min_perimeter.setObjectName("_min_perimeter")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self._min_perimeter)
        self.max_perimeter_lbl = QtWidgets.QLabel(self.groupBox)
        self.max_perimeter_lbl.setObjectName("max_perimeter_lbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.max_perimeter_lbl)
        self._max_perimeter = QtWidgets.QLineEdit(self.groupBox)
        self._max_perimeter.setMinimumSize(QtCore.QSize(50, 0))
        self._max_perimeter.setMaximumSize(QtCore.QSize(200, 16777215))
        self._max_perimeter.setFocusPolicy(QtCore.Qt.ClickFocus)
        self._max_perimeter.setObjectName("_max_perimeter")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self._max_perimeter)
        self.verticalLayout_12.addWidget(self.groupBox)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.contour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(90, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self._find_contour_btn = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._find_contour_btn.sizePolicy().hasHeightForWidth())
        self._find_contour_btn.setSizePolicy(sizePolicy)
        self._find_contour_btn.setCheckable(False)
        self._find_contour_btn.setChecked(False)
        self._find_contour_btn.setObjectName("_find_contour_btn")
        self.horizontalLayout_10.addWidget(self._find_contour_btn)
        self._crop_images_btn = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._crop_images_btn.sizePolicy().hasHeightForWidth())
        self._crop_images_btn.setSizePolicy(sizePolicy)
        self._crop_images_btn.setObjectName("_crop_images_btn")
        self.horizontalLayout_10.addWidget(self._crop_images_btn)
        self.gridLayout_3.addWidget(self.widget_5, 2, 0, 1, 1)
        self._apply_to_all_images_checkbox = QtWidgets.QCheckBox(self.contour)
        self._apply_to_all_images_checkbox.setChecked(False)
        self._apply_to_all_images_checkbox.setObjectName("_apply_to_all_images_checkbox")
        self.gridLayout_3.addWidget(self._apply_to_all_images_checkbox, 3, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_3)
        self.groupBox.raise_()
        self._contour_leaflet_tab.addTab(self.contour, "")
        self.groupBox_4 = QtWidgets.QGroupBox(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(20, 220))
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
" border: 1px solid gray;\n"
"border-radius: 9px;\n"
"margin-top: 0.5em;\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"left: 10px;\n"
"padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 1)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self._metadata_tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self._metadata_tableWidget.setObjectName("_metadata_tableWidget")
        self._metadata_tableWidget.setColumnCount(0)
        self._metadata_tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self._metadata_tableWidget)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 85))
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_15.setContentsMargins(12, 12, 0, 1)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self._apply_to_all_tables_empty_fields_checkbox = QtWidgets.QCheckBox(self.groupBox_10)
        self._apply_to_all_tables_empty_fields_checkbox.setAutoExclusive(True)
        self._apply_to_all_tables_empty_fields_checkbox.setTristate(False)
        self._apply_to_all_tables_empty_fields_checkbox.setObjectName("_apply_to_all_tables_empty_fields_checkbox")
        self.buttonGroup = QtWidgets.QButtonGroup(LeafInterrogatorMainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self._apply_to_all_tables_empty_fields_checkbox)
        self.verticalLayout_15.addWidget(self._apply_to_all_tables_empty_fields_checkbox)
        self._apply_to_all_tables_with_same_class_checkbox = QtWidgets.QCheckBox(self.groupBox_10)
        self._apply_to_all_tables_with_same_class_checkbox.setAutoExclusive(True)
        self._apply_to_all_tables_with_same_class_checkbox.setTristate(False)
        self._apply_to_all_tables_with_same_class_checkbox.setObjectName("_apply_to_all_tables_with_same_class_checkbox")
        self.buttonGroup.addButton(self._apply_to_all_tables_with_same_class_checkbox)
        self.verticalLayout_15.addWidget(self._apply_to_all_tables_with_same_class_checkbox)
        self._apply_to_all_tables_checkbox = QtWidgets.QCheckBox(self.groupBox_10)
        self._apply_to_all_tables_checkbox.setAutoExclusive(True)
        self._apply_to_all_tables_checkbox.setTristate(False)
        self._apply_to_all_tables_checkbox.setObjectName("_apply_to_all_tables_checkbox")
        self.buttonGroup.addButton(self._apply_to_all_tables_checkbox)
        self.verticalLayout_15.addWidget(self._apply_to_all_tables_checkbox)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.buttonGroup.addButton(self.checkBox)
        self.verticalLayout_15.addWidget(self.checkBox)
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._insert_metadata_button = QtWidgets.QPushButton(self.groupBox_4)
        self._insert_metadata_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self._insert_metadata_button.setObjectName("_insert_metadata_button")
        self.horizontalLayout.addWidget(self._insert_metadata_button)
        self._remove_row_button = QtWidgets.QPushButton(self.groupBox_4)
        self._remove_row_button.setMinimumSize(QtCore.QSize(20, 20))
        self._remove_row_button.setMaximumSize(QtCore.QSize(20, 20))
        self._remove_row_button.setObjectName("_remove_row_button")
        self.horizontalLayout.addWidget(self._remove_row_button)
        self._add_row_button = QtWidgets.QPushButton(self.groupBox_4)
        self._add_row_button.setMinimumSize(QtCore.QSize(20, 20))
        self._add_row_button.setMaximumSize(QtCore.QSize(20, 20))
        self._add_row_button.setObjectName("_add_row_button")
        self.horizontalLayout.addWidget(self._add_row_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.splitter_5)
        self.horizontalLayout_9.addWidget(self.splitter_6)
        self.main_tabs.addTab(self.tab_detect_contour, "")
        self.edit_contour = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_contour.sizePolicy().hasHeightForWidth())
        self.edit_contour.setSizePolicy(sizePolicy)
        self.edit_contour.setObjectName("edit_contour")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.edit_contour)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtWidgets.QSplitter(self.edit_contour)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_6 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self._edit_contour_opengl_widget = EditContourOpenGLWidget(self.widget_6)
        self._edit_contour_opengl_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self._edit_contour_opengl_widget.setObjectName("_edit_contour_opengl_widget")
        self.verticalLayout_5.addWidget(self._edit_contour_opengl_widget)
        self.widget = QtWidgets.QWidget(self.widget_6)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._edit_cnt_previous_btn = QtWidgets.QPushButton(self.widget)
        self._edit_cnt_previous_btn.setObjectName("_edit_cnt_previous_btn")
        self.horizontalLayout_2.addWidget(self._edit_cnt_previous_btn)
        self.widget_14 = QtWidgets.QWidget(self.widget)
        self.widget_14.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self._edit_cnt_counter_lineEdit = QtWidgets.QLineEdit(self.widget_14)
        self._edit_cnt_counter_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self._edit_cnt_counter_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self._edit_cnt_counter_lineEdit.setObjectName("_edit_cnt_counter_lineEdit")
        self.horizontalLayout_11.addWidget(self._edit_cnt_counter_lineEdit)
        self.label_7 = QtWidgets.QLabel(self.widget_14)
        self.label_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self._edit_cnt_counter_lbl = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._edit_cnt_counter_lbl.sizePolicy().hasHeightForWidth())
        self._edit_cnt_counter_lbl.setSizePolicy(sizePolicy)
        self._edit_cnt_counter_lbl.setMaximumSize(QtCore.QSize(30, 16777215))
        self._edit_cnt_counter_lbl.setSizeIncrement(QtCore.QSize(0, 0))
        self._edit_cnt_counter_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self._edit_cnt_counter_lbl.setObjectName("_edit_cnt_counter_lbl")
        self.horizontalLayout_11.addWidget(self._edit_cnt_counter_lbl)
        self._edit_cnt_counter_lineEdit.raise_()
        self._edit_cnt_counter_lbl.raise_()
        self.label_7.raise_()
        self.horizontalLayout_2.addWidget(self.widget_14)
        self._edit_cnt_next_btn = QtWidgets.QPushButton(self.widget)
        self._edit_cnt_next_btn.setObjectName("_edit_cnt_next_btn")
        self.horizontalLayout_2.addWidget(self._edit_cnt_next_btn)
        self.verticalLayout_5.addWidget(self.widget)
        self.widget_7 = QtWidgets.QWidget(self.splitter)
        self.widget_7.setMinimumSize(QtCore.QSize(150, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self._editing_tabs = QtWidgets.QTabWidget(self.widget_7)
        self._editing_tabs.setToolTip("")
        self._editing_tabs.setStyleSheet("QTreeWidget {\n"
"alternate-background-color: rgb(245, 245, 245);\n"
"background-color: rgb(230, 230, 230);\n"
"}\n"
"QTableWidget {\n"
"alternate-background-color: rgb(245, 245, 245);\n"
"background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"")
        self._editing_tabs.setObjectName("_editing_tabs")
        self.basic_tab = QtWidgets.QWidget()
        self.basic_tab.setObjectName("basic_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.basic_tab)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.basic_tab)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(12, 2, 11, 2)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.number_of_sample_points_lbl = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_of_sample_points_lbl.sizePolicy().hasHeightForWidth())
        self.number_of_sample_points_lbl.setSizePolicy(sizePolicy)
        self.number_of_sample_points_lbl.setObjectName("number_of_sample_points_lbl")
        self.gridLayout_2.addWidget(self.number_of_sample_points_lbl, 0, 0, 2, 1)
        self._edit_cnt_apply_to_all_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self._edit_cnt_apply_to_all_checkbox.setChecked(False)
        self._edit_cnt_apply_to_all_checkbox.setObjectName("_edit_cnt_apply_to_all_checkbox")
        self.gridLayout_2.addWidget(self._edit_cnt_apply_to_all_checkbox, 5, 0, 1, 1)
        self._number_of_points = QtWidgets.QLineEdit(self.groupBox_2)
        self._number_of_points.setMinimumSize(QtCore.QSize(50, 0))
        self._number_of_points.setMaximumSize(QtCore.QSize(50, 16777215))
        self._number_of_points.setObjectName("_number_of_points")
        self.gridLayout_2.addWidget(self._number_of_points, 0, 1, 2, 1)
        self._resample_btn = QtWidgets.QPushButton(self.groupBox_2)
        self._resample_btn.setMinimumSize(QtCore.QSize(100, 30))
        self._resample_btn.setObjectName("_resample_btn")
        self.gridLayout_2.addWidget(self._resample_btn, 3, 0, 1, 1)
        self._delete_resampled_contour_btn = QtWidgets.QPushButton(self.groupBox_2)
        self._delete_resampled_contour_btn.setObjectName("_delete_resampled_contour_btn")
        self.gridLayout_2.addWidget(self._delete_resampled_contour_btn, 3, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.mode_edit_contour_groupBox = QtWidgets.QGroupBox(self.basic_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_edit_contour_groupBox.sizePolicy().hasHeightForWidth())
        self.mode_edit_contour_groupBox.setSizePolicy(sizePolicy)
        self.mode_edit_contour_groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mode_edit_contour_groupBox.setObjectName("mode_edit_contour_groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mode_edit_contour_groupBox)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self._edit_contour_radiobtn = QtWidgets.QRadioButton(self.mode_edit_contour_groupBox)
        self._edit_contour_radiobtn.setChecked(True)
        self._edit_contour_radiobtn.setObjectName("_edit_contour_radiobtn")
        self.verticalLayout_7.addWidget(self._edit_contour_radiobtn)
        self.line = QtWidgets.QFrame(self.mode_edit_contour_groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self._edit_landmarks_radiobtn = QtWidgets.QRadioButton(self.mode_edit_contour_groupBox)
        self._edit_landmarks_radiobtn.setObjectName("_edit_landmarks_radiobtn")
        self.verticalLayout_7.addWidget(self._edit_landmarks_radiobtn)
        self._show_suggested_landmarks_checkbox = QtWidgets.QCheckBox(self.mode_edit_contour_groupBox)
        self._show_suggested_landmarks_checkbox.setEnabled(False)
        self._show_suggested_landmarks_checkbox.setObjectName("_show_suggested_landmarks_checkbox")
        self.verticalLayout_7.addWidget(self._show_suggested_landmarks_checkbox)
        self._show_all_landmarks_checkbox = QtWidgets.QCheckBox(self.mode_edit_contour_groupBox)
        self._show_all_landmarks_checkbox.setEnabled(False)
        self._show_all_landmarks_checkbox.setObjectName("_show_all_landmarks_checkbox")
        self.verticalLayout_7.addWidget(self._show_all_landmarks_checkbox)
        self._redefine_landmarks_checkbox = QtWidgets.QCheckBox(self.mode_edit_contour_groupBox)
        self._redefine_landmarks_checkbox.setEnabled(False)
        self._redefine_landmarks_checkbox.setObjectName("_redefine_landmarks_checkbox")
        self.verticalLayout_7.addWidget(self._redefine_landmarks_checkbox)
        self.widget_8 = QtWidgets.QWidget(self.mode_edit_contour_groupBox)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_8.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_7.addWidget(self.widget_8)
        self._shift_landmarks_anticlockwise_button = QtWidgets.QPushButton(self.mode_edit_contour_groupBox)
        self._shift_landmarks_anticlockwise_button.setMaximumSize(QtCore.QSize(150, 16777215))
        self._shift_landmarks_anticlockwise_button.setObjectName("_shift_landmarks_anticlockwise_button")
        self.verticalLayout_7.addWidget(self._shift_landmarks_anticlockwise_button)
        self._edited_contour_save_changes_btn = QtWidgets.QPushButton(self.mode_edit_contour_groupBox)
        self._edited_contour_save_changes_btn.setObjectName("_edited_contour_save_changes_btn")
        self.verticalLayout_7.addWidget(self._edited_contour_save_changes_btn)
        self.verticalLayout_9.addWidget(self.mode_edit_contour_groupBox)
        self._editing_tabs.addTab(self.basic_tab, "")
        self.registration_tab = QtWidgets.QWidget()
        self.registration_tab.setObjectName("registration_tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.registration_tab)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self._registration_treeWidget = QtWidgets.QTreeWidget(self.registration_tab)
        self._registration_treeWidget.setAutoFillBackground(False)
        self._registration_treeWidget.setStyleSheet("QTreeWidget {\n"
"alternate-background-color: rgb(245, 245, 245);\n"
"background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self._registration_treeWidget.setAlternatingRowColors(True)
        self._registration_treeWidget.setObjectName("_registration_treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self._registration_treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self._registration_treeWidget)
        self._registration_treeWidget.header().setVisible(False)
        self._registration_treeWidget.header().setCascadingSectionResizes(False)
        self.verticalLayout_11.addWidget(self._registration_treeWidget)
        self._apply_registration_btn = QtWidgets.QPushButton(self.registration_tab)
        self._apply_registration_btn.setObjectName("_apply_registration_btn")
        self.verticalLayout_11.addWidget(self._apply_registration_btn)
        self._editing_tabs.addTab(self.registration_tab, "")
        self.processes_tab = QtWidgets.QWidget()
        self.processes_tab.setObjectName("processes_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.processes_tab)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.splitter_2 = QtWidgets.QSplitter(self.processes_tab)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self._processes_treeWidget = QtWidgets.QTreeWidget(self.splitter_2)
        self._processes_treeWidget.setMouseTracking(True)
        self._processes_treeWidget.setAlternatingRowColors(True)
        self._processes_treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self._processes_treeWidget.setObjectName("_processes_treeWidget")
        self._processes_treeWidget.header().setVisible(False)
        self._processes_treeWidget.header().setCascadingSectionResizes(False)
        self._process_parameters_tablewidget = QtWidgets.QTableWidget(self.splitter_2)
        self._process_parameters_tablewidget.setMinimumSize(QtCore.QSize(0, 0))
        self._process_parameters_tablewidget.setAutoFillBackground(False)
        self._process_parameters_tablewidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._process_parameters_tablewidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self._process_parameters_tablewidget.setLineWidth(1)
        self._process_parameters_tablewidget.setMidLineWidth(1)
        self._process_parameters_tablewidget.setAlternatingRowColors(True)
        self._process_parameters_tablewidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self._process_parameters_tablewidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self._process_parameters_tablewidget.setRowCount(0)
        self._process_parameters_tablewidget.setColumnCount(2)
        self._process_parameters_tablewidget.setObjectName("_process_parameters_tablewidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self._process_parameters_tablewidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self._process_parameters_tablewidget.setHorizontalHeaderItem(1, item)
        self._process_parameters_tablewidget.horizontalHeader().setDefaultSectionSize(130)
        self._process_parameters_tablewidget.horizontalHeader().setSortIndicatorShown(False)
        self._process_parameters_tablewidget.horizontalHeader().setStretchLastSection(True)
        self._process_parameters_tablewidget.verticalHeader().setVisible(False)
        self._process_parameters_tablewidget.verticalHeader().setCascadingSectionResizes(True)
        self._process_parameters_tablewidget.verticalHeader().setSortIndicatorShown(False)
        self._process_parameters_tablewidget.verticalHeader().setStretchLastSection(False)
        self._result_tableWidget = QtWidgets.QTableWidget(self.splitter_2)
        self._result_tableWidget.setStyleSheet("QTableWidget {alternate-background-color:rgb(190, 255, 255) ;\n"
"background-color: rgb(130, 255, 255);}")
        self._result_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self._result_tableWidget.setAlternatingRowColors(True)
        self._result_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self._result_tableWidget.setObjectName("_result_tableWidget")
        self._result_tableWidget.setColumnCount(2)
        self._result_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self._result_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self._result_tableWidget.setHorizontalHeaderItem(1, item)
        self._result_tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self._result_tableWidget.horizontalHeader().setMinimumSectionSize(19)
        self._result_tableWidget.horizontalHeader().setStretchLastSection(True)
        self._result_tableWidget.verticalHeader().setVisible(False)
        self._result_tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self._start_process_btn = QtWidgets.QPushButton(self.layoutWidget)
        self._start_process_btn.setObjectName("_start_process_btn")
        self.horizontalLayout_6.addWidget(self._start_process_btn)
        self.verticalLayout_10.addWidget(self.splitter_2)
        self._editing_tabs.addTab(self.processes_tab, "")
        self.verticalLayout_8.addWidget(self._editing_tabs)
        self.verticalLayout_6.addWidget(self.splitter)
        self.main_tabs.addTab(self.edit_contour, "")
        self.tab_shape_space = QtWidgets.QWidget()
        self.tab_shape_space.setObjectName("tab_shape_space")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_shape_space)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_4 = QtWidgets.QSplitter(self.tab_shape_space)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.plot_groupBox = QtWidgets.QGroupBox(self.splitter_4)
        self.plot_groupBox.setTitle("")
        self.plot_groupBox.setObjectName("plot_groupBox")
        self._shape_space_tab_horizontal_layout = QtWidgets.QHBoxLayout(self.plot_groupBox)
        self._shape_space_tab_horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self._shape_space_tab_horizontal_layout.setSpacing(6)
        self._shape_space_tab_horizontal_layout.setObjectName("_shape_space_tab_horizontal_layout")
        self._tab_plot = QtWidgets.QTabWidget(self.splitter_4)
        self._tab_plot.setMaximumSize(QtCore.QSize(250, 16777215))
        self._tab_plot.setObjectName("_tab_plot")
        self._tab_tweaks = QtWidgets.QWidget()
        self._tab_tweaks.setObjectName("_tab_tweaks")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self._tab_tweaks)
        self.verticalLayout_17.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_11 = QtWidgets.QWidget(self._tab_tweaks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(6)
        self.gridLayout_7.setVerticalSpacing(1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget_11)
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_2 = QtWidgets.QLabel(self.groupBox_9)
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_9)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_9)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 2, 0, 1, 1)
        self._y_percent_lbl = QtWidgets.QLabel(self.groupBox_9)
        self._y_percent_lbl.setObjectName("_y_percent_lbl")
        self.gridLayout_11.addWidget(self._y_percent_lbl, 1, 1, 1, 1)
        self._total_variance_lbl = QtWidgets.QLabel(self.groupBox_9)
        self._total_variance_lbl.setObjectName("_total_variance_lbl")
        self.gridLayout_11.addWidget(self._total_variance_lbl, 2, 1, 1, 1)
        self._x_percent_lbl = QtWidgets.QLabel(self.groupBox_9)
        self._x_percent_lbl.setObjectName("_x_percent_lbl")
        self.gridLayout_11.addWidget(self._x_percent_lbl, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_9, 15, 0, 1, 2)
        self._z_axis_widget = QtWidgets.QWidget(self.widget_11)
        self._z_axis_widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self._z_axis_widget.setObjectName("_z_axis_widget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self._z_axis_widget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gridLayout_7.addWidget(self._z_axis_widget, 13, 1, 1, 1)
        self._y_axis_widget = QtWidgets.QWidget(self.widget_11)
        self._y_axis_widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self._y_axis_widget.setObjectName("_y_axis_widget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self._y_axis_widget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gridLayout_7.addWidget(self._y_axis_widget, 12, 1, 1, 1)
        self._export_components_btn = QtWidgets.QPushButton(self.widget_11)
        self._export_components_btn.setObjectName("_export_components_btn")
        self.gridLayout_7.addWidget(self._export_components_btn, 17, 0, 1, 2)
        self._y_axis_combo_box = QtWidgets.QComboBox(self.widget_11)
        self._y_axis_combo_box.setObjectName("_y_axis_combo_box")
        self.gridLayout_7.addWidget(self._y_axis_combo_box, 11, 1, 1, 1)
        self.x_axis_lbl = QtWidgets.QLabel(self.widget_11)
        self.x_axis_lbl.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_axis_lbl.setObjectName("x_axis_lbl")
        self.gridLayout_7.addWidget(self.x_axis_lbl, 9, 0, 1, 1)
        self.y_axis_lbl = QtWidgets.QLabel(self.widget_11)
        self.y_axis_lbl.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_axis_lbl.setObjectName("y_axis_lbl")
        self.gridLayout_7.addWidget(self.y_axis_lbl, 11, 0, 1, 1)
        self._apply_shape_space_plot_conf_button = QtWidgets.QPushButton(self.widget_11)
        self._apply_shape_space_plot_conf_button.setObjectName("_apply_shape_space_plot_conf_button")
        self.gridLayout_7.addWidget(self._apply_shape_space_plot_conf_button, 14, 0, 1, 2)
        self._x_axis_combo_box = QtWidgets.QComboBox(self.widget_11)
        self._x_axis_combo_box.setObjectName("_x_axis_combo_box")
        self.gridLayout_7.addWidget(self._x_axis_combo_box, 9, 1, 1, 1)
        self._x_axis_widget = QtWidgets.QWidget(self.widget_11)
        self._x_axis_widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self._x_axis_widget.setObjectName("_x_axis_widget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self._x_axis_widget)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout_7.addWidget(self._x_axis_widget, 10, 1, 1, 1)
        self._shape_space_components_holder_widget = QtWidgets.QWidget(self.widget_11)
        self._shape_space_components_holder_widget.setEnabled(True)
        self._shape_space_components_holder_widget.setMaximumSize(QtCore.QSize(16777215, 180))
        self._shape_space_components_holder_widget.setObjectName("_shape_space_components_holder_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self._shape_space_components_holder_widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self._efd_size_invariant_checkbox = QtWidgets.QCheckBox(self._shape_space_components_holder_widget)
        self._efd_size_invariant_checkbox.setObjectName("_efd_size_invariant_checkbox")
        self.gridLayout_5.addWidget(self._efd_size_invariant_checkbox, 3, 1, 1, 1)
        self._efd_normalize_checkbox = QtWidgets.QCheckBox(self._shape_space_components_holder_widget)
        self._efd_normalize_checkbox.setObjectName("_efd_normalize_checkbox")
        self.gridLayout_5.addWidget(self._efd_normalize_checkbox, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self._shape_space_components_holder_widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self._harmonic_coeffs_groupbox = QtWidgets.QGroupBox(self._shape_space_components_holder_widget)
        self._harmonic_coeffs_groupbox.setMinimumSize(QtCore.QSize(0, 60))
        self._harmonic_coeffs_groupbox.setMaximumSize(QtCore.QSize(16777215, 70))
        self._harmonic_coeffs_groupbox.setObjectName("_harmonic_coeffs_groupbox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self._harmonic_coeffs_groupbox)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_12 = QtWidgets.QWidget(self._harmonic_coeffs_groupbox)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self._asymmetric_components_check_box = QtWidgets.QCheckBox(self.widget_12)
        self._asymmetric_components_check_box.setChecked(True)
        self._asymmetric_components_check_box.setObjectName("_asymmetric_components_check_box")
        self.gridLayout_8.addWidget(self._asymmetric_components_check_box, 1, 0, 1, 1)
        self._symmetric_components_check_box = QtWidgets.QCheckBox(self.widget_12)
        self._symmetric_components_check_box.setChecked(True)
        self._symmetric_components_check_box.setObjectName("_symmetric_components_check_box")
        self.gridLayout_8.addWidget(self._symmetric_components_check_box, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.widget_12)
        self.gridLayout_5.addWidget(self._harmonic_coeffs_groupbox, 6, 0, 1, 2)
        self._number_of_harmonics = QtWidgets.QLineEdit(self._shape_space_components_holder_widget)
        self._number_of_harmonics.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self._number_of_harmonics.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._number_of_harmonics.setObjectName("_number_of_harmonics")
        self.gridLayout_5.addWidget(self._number_of_harmonics, 1, 1, 1, 1)
        self._number_of_harmonics_lbl = QtWidgets.QLabel(self._shape_space_components_holder_widget)
        self._number_of_harmonics_lbl.setObjectName("_number_of_harmonics_lbl")
        self.gridLayout_5.addWidget(self._number_of_harmonics_lbl, 1, 0, 1, 1)
        self._method_combo_box = QtWidgets.QComboBox(self._shape_space_components_holder_widget)
        self._method_combo_box.setEnabled(True)
        self._method_combo_box.setObjectName("_method_combo_box")
        self._method_combo_box.addItem("")
        self.gridLayout_5.addWidget(self._method_combo_box, 0, 1, 1, 1)
        self._lda_options_widget = QtWidgets.QWidget(self._shape_space_components_holder_widget)
        self._lda_options_widget.setObjectName("_lda_options_widget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self._lda_options_widget)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_5.addWidget(self._lda_options_widget, 7, 0, 1, 2)
        self._method_combo_box.raise_()
        self.label.raise_()
        self._number_of_harmonics.raise_()
        self._number_of_harmonics_lbl.raise_()
        self._harmonic_coeffs_groupbox.raise_()
        self._efd_normalize_checkbox.raise_()
        self._efd_size_invariant_checkbox.raise_()
        self._lda_options_widget.raise_()
        self.gridLayout_7.addWidget(self._shape_space_components_holder_widget, 1, 0, 1, 2)
        self._x_axis_combo_box.raise_()
        self.x_axis_lbl.raise_()
        self._y_axis_combo_box.raise_()
        self.y_axis_lbl.raise_()
        self._apply_shape_space_plot_conf_button.raise_()
        self._export_components_btn.raise_()
        self.groupBox_9.raise_()
        self._shape_space_components_holder_widget.raise_()
        self._y_axis_widget.raise_()
        self._z_axis_widget.raise_()
        self._x_axis_widget.raise_()
        self.verticalLayout_17.addWidget(self.widget_11)
        self._tab_plot.addTab(self._tab_tweaks, "")
        self._tab_plot_options_3 = QtWidgets.QWidget()
        self._tab_plot_options_3.setObjectName("_tab_plot_options_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self._tab_plot_options_3)
        self.verticalLayout_18.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_9 = QtWidgets.QWidget(self._tab_plot_options_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 114))
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(6)
        self.gridLayout_6.setVerticalSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_9)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setContentsMargins(11, 6, 11, 0)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self._number_of_std_lbl = QtWidgets.QLabel(self.groupBox_5)
        self._number_of_std_lbl.setObjectName("_number_of_std_lbl")
        self.gridLayout_9.addWidget(self._number_of_std_lbl, 1, 0, 1, 1)
        self._number_of_std = QtWidgets.QLineEdit(self.groupBox_5)
        self._number_of_std.setObjectName("_number_of_std")
        self.gridLayout_9.addWidget(self._number_of_std, 1, 2, 1, 1)
        self._number_of_std_curves_lbl = QtWidgets.QLabel(self.groupBox_5)
        self._number_of_std_curves_lbl.setObjectName("_number_of_std_curves_lbl")
        self.gridLayout_9.addWidget(self._number_of_std_curves_lbl, 2, 0, 1, 2)
        self._number_of_std_curves = QtWidgets.QLineEdit(self.groupBox_5)
        self._number_of_std_curves.setObjectName("_number_of_std_curves")
        self.gridLayout_9.addWidget(self._number_of_std_curves, 2, 2, 1, 1)
        self._show_std_ellipse_check_box = QtWidgets.QCheckBox(self.groupBox_5)
        self._show_std_ellipse_check_box.setObjectName("_show_std_ellipse_check_box")
        self.gridLayout_9.addWidget(self._show_std_ellipse_check_box, 0, 0, 1, 1)
        self._show_std_error_ellipse_check_box = QtWidgets.QCheckBox(self.groupBox_5)
        self._show_std_error_ellipse_check_box.setObjectName("_show_std_error_ellipse_check_box")
        self.gridLayout_9.addWidget(self._show_std_error_ellipse_check_box, 0, 1, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_5, 3, 0, 1, 2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget_9)
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 250))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setContentsMargins(12, 12, 11, 0)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self._shape_space_plot_background_image_zoom = QtWidgets.QLineEdit(self.groupBox_8)
        self._shape_space_plot_background_image_zoom.setObjectName("_shape_space_plot_background_image_zoom")
        self.gridLayout_10.addWidget(self._shape_space_plot_background_image_zoom, 5, 1, 1, 1)
        self._shape_space_plot_show_back_ground_annotation_images_check_box = QtWidgets.QCheckBox(self.groupBox_8)
        self._shape_space_plot_show_back_ground_annotation_images_check_box.setChecked(True)
        self._shape_space_plot_show_back_ground_annotation_images_check_box.setObjectName("_shape_space_plot_show_back_ground_annotation_images_check_box")
        self.gridLayout_10.addWidget(self._shape_space_plot_show_back_ground_annotation_images_check_box, 6, 0, 1, 2)
        self._shape_space_plot_lim_lbl = QtWidgets.QLabel(self.groupBox_8)
        self._shape_space_plot_lim_lbl.setObjectName("_shape_space_plot_lim_lbl")
        self.gridLayout_10.addWidget(self._shape_space_plot_lim_lbl, 0, 0, 1, 1)
        self._shape_space_plot_lim = QtWidgets.QLineEdit(self.groupBox_8)
        self._shape_space_plot_lim.setFocusPolicy(QtCore.Qt.ClickFocus)
        self._shape_space_plot_lim.setObjectName("_shape_space_plot_lim")
        self.gridLayout_10.addWidget(self._shape_space_plot_lim, 0, 1, 1, 1)
        self._shape_space_plot_background_number_of_rows_lbl = QtWidgets.QLabel(self.groupBox_8)
        self._shape_space_plot_background_number_of_rows_lbl.setObjectName("_shape_space_plot_background_number_of_rows_lbl")
        self.gridLayout_10.addWidget(self._shape_space_plot_background_number_of_rows_lbl, 2, 0, 1, 1)
        self._shape_space_plot_background_number_of_columns = QtWidgets.QLineEdit(self.groupBox_8)
        self._shape_space_plot_background_number_of_columns.setObjectName("_shape_space_plot_background_number_of_columns")
        self.gridLayout_10.addWidget(self._shape_space_plot_background_number_of_columns, 3, 1, 1, 1)
        self._shape_space_plot_background_number_of_columns_lbl = QtWidgets.QLabel(self.groupBox_8)
        self._shape_space_plot_background_number_of_columns_lbl.setObjectName("_shape_space_plot_background_number_of_columns_lbl")
        self.gridLayout_10.addWidget(self._shape_space_plot_background_number_of_columns_lbl, 3, 0, 1, 1)
        self._shape_space_plot_background_number_of_rows = QtWidgets.QLineEdit(self.groupBox_8)
        self._shape_space_plot_background_number_of_rows.setObjectName("_shape_space_plot_background_number_of_rows")
        self.gridLayout_10.addWidget(self._shape_space_plot_background_number_of_rows, 2, 1, 1, 1)
        self._shape_space_plot_background_image_size_label = QtWidgets.QLabel(self.groupBox_8)
        self._shape_space_plot_background_image_size_label.setObjectName("_shape_space_plot_background_image_size_label")
        self.gridLayout_10.addWidget(self._shape_space_plot_background_image_size_label, 5, 0, 1, 1)
        self._shape_space_plot_point_size_lbl = QtWidgets.QLabel(self.groupBox_8)
        self._shape_space_plot_point_size_lbl.setObjectName("_shape_space_plot_point_size_lbl")
        self.gridLayout_10.addWidget(self._shape_space_plot_point_size_lbl, 1, 0, 1, 1)
        self._shape_space_plot_point_size = QtWidgets.QLineEdit(self.groupBox_8)
        self._shape_space_plot_point_size.setObjectName("_shape_space_plot_point_size")
        self.gridLayout_10.addWidget(self._shape_space_plot_point_size, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 4, 0, 1, 1)
        self._shape_space_plot_background_image_rotation = QtWidgets.QLineEdit(self.groupBox_8)
        self._shape_space_plot_background_image_rotation.setObjectName("_shape_space_plot_background_image_rotation")
        self.gridLayout_10.addWidget(self._shape_space_plot_background_image_rotation, 4, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_8, 5, 0, 1, 2)
        self._shape_space_image_graphic_view = QtWidgets.QGraphicsView(self.widget_9)
        self._shape_space_image_graphic_view.setObjectName("_shape_space_image_graphic_view")
        self.gridLayout_6.addWidget(self._shape_space_image_graphic_view, 2, 0, 1, 1)
        self._show_centroid_check_box = QtWidgets.QCheckBox(self.widget_9)
        self._show_centroid_check_box.setObjectName("_show_centroid_check_box")
        self.gridLayout_6.addWidget(self._show_centroid_check_box, 4, 0, 1, 1)
        self._apply_plot_options_btn = QtWidgets.QPushButton(self.widget_9)
        self._apply_plot_options_btn.setObjectName("_apply_plot_options_btn")
        self.gridLayout_6.addWidget(self._apply_plot_options_btn, 6, 0, 1, 2)
        self._shape_space_image_lbl = QtWidgets.QLabel(self.widget_9)
        self._shape_space_image_lbl.setMinimumSize(QtCore.QSize(0, 0))
        self._shape_space_image_lbl.setText("")
        self._shape_space_image_lbl.setObjectName("_shape_space_image_lbl")
        self.gridLayout_6.addWidget(self._shape_space_image_lbl, 1, 0, 1, 1)
        self.verticalLayout_18.addWidget(self.widget_9)
        self._tab_plot.addTab(self._tab_plot_options_3, "")
        self._tab_colors_2 = QtWidgets.QWidget()
        self._tab_colors_2.setObjectName("_tab_colors_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self._tab_colors_2)
        self.verticalLayout_19.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self._colors_and_classes_scroll_area = QtWidgets.QScrollArea(self._tab_colors_2)
        self._colors_and_classes_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self._colors_and_classes_scroll_area.setWidgetResizable(True)
        self._colors_and_classes_scroll_area.setObjectName("_colors_and_classes_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 84, 28))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self._scroll_area_widget_contents_gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self._scroll_area_widget_contents_gridLayout.setContentsMargins(0, 0, 0, 0)
        self._scroll_area_widget_contents_gridLayout.setSpacing(6)
        self._scroll_area_widget_contents_gridLayout.setObjectName("_scroll_area_widget_contents_gridLayout")
        self._colors_and_classes_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_19.addWidget(self._colors_and_classes_scroll_area)
        self._tab_plot.addTab(self._tab_colors_2, "")
        self.horizontalLayout_4.addWidget(self.splitter_4)
        self.main_tabs.addTab(self.tab_shape_space, "")
        self.horizontalLayout_3.addWidget(self.main_tabs)
        LeafInterrogatorMainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(LeafInterrogatorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 947, 20))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        LeafInterrogatorMainWindow.setMenuBar(self.menubar)
        self._mainToolBar = QtWidgets.QToolBar(LeafInterrogatorMainWindow)
        self._mainToolBar.setObjectName("_mainToolBar")
        LeafInterrogatorMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self._mainToolBar)
        self.action_open = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_open.setObjectName("action_open")
        self.actionZoom_In = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_out = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.action_open_folder = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_open_folder.setObjectName("action_open_folder")
        self.action_save = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_save.setObjectName("action_save")
        self.action_quit = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_quit.setObjectName("action_quit")
        self.actionRotate_Left = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.actionRotate_Left.setObjectName("actionRotate_Left")
        self.actionUndo = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionRotate_Right = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.actionRotate_Right.setObjectName("actionRotate_Right")
        self.actionReset_to_default = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.actionReset_to_default.setObjectName("actionReset_to_default")
        self.actionDelete = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.action_load_project = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_load_project.setObjectName("action_load_project")
        self.action_save_project = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_save_project.setObjectName("action_save_project")
        self.action_ocr = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_ocr.setObjectName("action_ocr")
        self.action_metadata_from_image_name = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_metadata_from_image_name.setObjectName("action_metadata_from_image_name")
        self.action_save_all = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_save_all.setObjectName("action_save_all")
        self.action_import_contours_csv_files = QtWidgets.QAction(LeafInterrogatorMainWindow)
        self.action_import_contours_csv_files.setObjectName("action_import_contours_csv_files")
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.action_open_folder)
        self.menuFile.addAction(self.action_load_project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_save_project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menuView.addAction(self.actionZoom_In)
        self.menuView.addAction(self.actionZoom_out)
        self.menuView.addAction(self.actionReset_to_default)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionRotate_Left)
        self.menuView.addAction(self.actionRotate_Right)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDelete)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self._mainToolBar.addSeparator()
        self.threshhold_lbl.setBuddy(self._threshold)
        self.min_perimeter_lbl.setBuddy(self._min_perimeter)

        self.retranslateUi(LeafInterrogatorMainWindow)
        self.main_tabs.setCurrentIndex(0)
        self._contour_leaflet_tab.setCurrentIndex(0)
        self._editing_tabs.setCurrentIndex(0)
        self._tab_plot.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LeafInterrogatorMainWindow)

    def retranslateUi(self, LeafInterrogatorMainWindow):
        _translate = QtCore.QCoreApplication.translate
        LeafInterrogatorMainWindow.setWindowTitle(_translate("LeafInterrogatorMainWindow", "Leaf Interrogator"))
        self._image_opengl_widget.setToolTip(_translate("LeafInterrogatorMainWindow", "<html><head/><body><p>Shortcuts: </p><p>Zoom:<span style=\" font-weight:600;\"> Scroll</span></p><p>Move image: <span style=\" font-weight:600;\">Hold Alt + Hold Left-Click</span></p></body></html>"))
        self.previous_image_btn.setText(_translate("LeafInterrogatorMainWindow", "<"))
        self._image_counter_lineEdit.setText(_translate("LeafInterrogatorMainWindow", "0"))
        self.label_5.setText(_translate("LeafInterrogatorMainWindow", "/"))
        self.image_counter_label.setText(_translate("LeafInterrogatorMainWindow", "0"))
        self.next_image_btn.setText(_translate("LeafInterrogatorMainWindow", ">"))
        self._contour_opengl_widget.setToolTip(_translate("LeafInterrogatorMainWindow", "<html><head/><body><p>Shortcuts: </p><p>Zoom:<span style=\" font-weight:600;\"> Scroll</span></p><p>Moveimage: <span style=\" font-weight:600;\">Hold Alt + Hold Left-Click</span></p></body></html>"))
        self.groupBox.setTitle(_translate("LeafInterrogatorMainWindow", "Tweak"))
        self.threshhold_lbl.setText(_translate("LeafInterrogatorMainWindow", "Treshold:"))
        self._threshold.setText(_translate("LeafInterrogatorMainWindow", "170"))
        self.min_perimeter_lbl.setText(_translate("LeafInterrogatorMainWindow", "Min Perimeter:"))
        self._min_perimeter.setText(_translate("LeafInterrogatorMainWindow", "300"))
        self.max_perimeter_lbl.setText(_translate("LeafInterrogatorMainWindow", "Max Perimeter:"))
        self._max_perimeter.setText(_translate("LeafInterrogatorMainWindow", "8000"))
        self._find_contour_btn.setToolTip(_translate("LeafInterrogatorMainWindow", "Find all contours (leafs) of the images."))
        self._find_contour_btn.setText(_translate("LeafInterrogatorMainWindow", "Find Contour"))
        self._crop_images_btn.setToolTip(_translate("LeafInterrogatorMainWindow", "If there is more than one leaf (contour) in the image, \n"
"this button will separate them into individual images."))
        self._crop_images_btn.setText(_translate("LeafInterrogatorMainWindow", "Crop Contours"))
        self._apply_to_all_images_checkbox.setText(_translate("LeafInterrogatorMainWindow", "Apply To All Images"))
        self._contour_leaflet_tab.setTabText(self._contour_leaflet_tab.indexOf(self.contour), _translate("LeafInterrogatorMainWindow", "Contour"))
        self.groupBox_4.setTitle(_translate("LeafInterrogatorMainWindow", "Metadata Table"))
        self.groupBox_10.setTitle(_translate("LeafInterrogatorMainWindow", "Apply To"))
        self._apply_to_all_tables_empty_fields_checkbox.setText(_translate("LeafInterrogatorMainWindow", "All Tables With Empty Fields"))
        self._apply_to_all_tables_with_same_class_checkbox.setText(_translate("LeafInterrogatorMainWindow", "All Tables With Same Class"))
        self._apply_to_all_tables_checkbox.setText(_translate("LeafInterrogatorMainWindow", "All Tables"))
        self.checkBox.setText(_translate("LeafInterrogatorMainWindow", "Current Table"))
        self._insert_metadata_button.setText(_translate("LeafInterrogatorMainWindow", "Commit Changes"))
        self._remove_row_button.setText(_translate("LeafInterrogatorMainWindow", "-"))
        self._add_row_button.setText(_translate("LeafInterrogatorMainWindow", "+"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.tab_detect_contour), _translate("LeafInterrogatorMainWindow", "Detect Contour"))
        self._edit_contour_opengl_widget.setToolTip(_translate("LeafInterrogatorMainWindow", "<html><head/><body><p>Shortcuts for editing contours:</p><p>- Select a point: mouse <span style=\" font-weight:600;\">Left-Click</span></p><p>- Delete a point from contour: 1. select a point 2. press <span style=\" font-weight:600;\">Backspace (Delete </span>on mac<span style=\" font-weight:600;\">)</span></p><p>- Add a point to a contour: <span style=\" font-weight:600;\">Hold Control (Command </span>on mac<span style=\" font-weight:600;\">) + Left-Click </span>on desired position</p><p>- Remove part of the contour: <span style=\" font-weight:600;\">Hold Shift </span>and <span style=\" font-weight:600;\">Left-Click </span>on start and end position. <span style=\" font-weight:600; font-style:italic;\">Note:</span><span style=\" font-style:italic;\"> The contour direction of removing is </span><span style=\" font-weight:600; font-style:italic;\">Anti-Clockwise.</span></p><p>Shortcuts for editing landmarks:</p><p>- For add a landmark: <span style=\" font-weight:600;\">Hold Control (Command </span>on mac<span style=\" font-weight:600;\">) + Left-Click </span>on contour. <span style=\" font-weight:600; font-style:italic;\">Note: </span><span style=\" font-style:italic;\">The order (position) of the landmarks are important for registration methods. They can be differentiated by color. </span></p><p><br/></p></body></html>"))
        self._edit_cnt_previous_btn.setText(_translate("LeafInterrogatorMainWindow", "<"))
        self._edit_cnt_counter_lineEdit.setText(_translate("LeafInterrogatorMainWindow", "0"))
        self.label_7.setText(_translate("LeafInterrogatorMainWindow", "/"))
        self._edit_cnt_counter_lbl.setText(_translate("LeafInterrogatorMainWindow", "0"))
        self._edit_cnt_next_btn.setText(_translate("LeafInterrogatorMainWindow", ">"))
        self.groupBox_2.setTitle(_translate("LeafInterrogatorMainWindow", "Resampling Options"))
        self.number_of_sample_points_lbl.setText(_translate("LeafInterrogatorMainWindow", "Number of sample points:"))
        self._edit_cnt_apply_to_all_checkbox.setText(_translate("LeafInterrogatorMainWindow", "Apply To All Contours"))
        self._number_of_points.setToolTip(_translate("LeafInterrogatorMainWindow", "<html><head/><body><p>Number of points between each two landmarks.</p></body></html>"))
        self._number_of_points.setText(_translate("LeafInterrogatorMainWindow", "60"))
        self._resample_btn.setText(_translate("LeafInterrogatorMainWindow", "Resample"))
        self._delete_resampled_contour_btn.setText(_translate("LeafInterrogatorMainWindow", "Revert"))
        self.mode_edit_contour_groupBox.setTitle(_translate("LeafInterrogatorMainWindow", "Changing Mode"))
        self._edit_contour_radiobtn.setText(_translate("LeafInterrogatorMainWindow", "Edit contour points"))
        self._edit_landmarks_radiobtn.setText(_translate("LeafInterrogatorMainWindow", "Edit Landmarks"))
        self._show_suggested_landmarks_checkbox.setText(_translate("LeafInterrogatorMainWindow", "Show suggested landmarks"))
        self._show_all_landmarks_checkbox.setText(_translate("LeafInterrogatorMainWindow", "Show all landmarks"))
        self._redefine_landmarks_checkbox.setText(_translate("LeafInterrogatorMainWindow", "Redefine landmarks"))
        self._shift_landmarks_anticlockwise_button.setToolTip(_translate("LeafInterrogatorMainWindow", "Rotate landmarks in anti-clockwise order.\n"
"If contour was resampled before editing the landmarks,\n"
"it will resample it again based on the new defined landmarks."))
        self._shift_landmarks_anticlockwise_button.setText(_translate("LeafInterrogatorMainWindow", "Shift Landmarks"))
        self._edited_contour_save_changes_btn.setToolTip(_translate("LeafInterrogatorMainWindow", "Save all changes."))
        self._edited_contour_save_changes_btn.setText(_translate("LeafInterrogatorMainWindow", "Save changes"))
        self._editing_tabs.setTabText(self._editing_tabs.indexOf(self.basic_tab), _translate("LeafInterrogatorMainWindow", "Basic"))
        self._registration_treeWidget.headerItem().setText(0, _translate("LeafInterrogatorMainWindow", "Alignment & Registration"))
        __sortingEnabled = self._registration_treeWidget.isSortingEnabled()
        self._registration_treeWidget.setSortingEnabled(False)
        self._registration_treeWidget.topLevelItem(0).setText(0, _translate("LeafInterrogatorMainWindow", "Translation and rotation"))
        self._registration_treeWidget.topLevelItem(0).child(0).setText(0, _translate("LeafInterrogatorMainWindow", "Align main-axis (2 Point)"))
        self._registration_treeWidget.setSortingEnabled(__sortingEnabled)
        self._apply_registration_btn.setText(_translate("LeafInterrogatorMainWindow", "Apply"))
        self._editing_tabs.setTabText(self._editing_tabs.indexOf(self.registration_tab), _translate("LeafInterrogatorMainWindow", "Registration"))
        self._processes_treeWidget.headerItem().setText(0, _translate("LeafInterrogatorMainWindow", "Process"))
        self._process_parameters_tablewidget.setSortingEnabled(False)
        item = self._process_parameters_tablewidget.horizontalHeaderItem(0)
        item.setText(_translate("LeafInterrogatorMainWindow", "Parameter"))
        item = self._process_parameters_tablewidget.horizontalHeaderItem(1)
        item.setText(_translate("LeafInterrogatorMainWindow", "Value"))
        item = self._result_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("LeafInterrogatorMainWindow", "Result"))
        item = self._result_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("LeafInterrogatorMainWindow", "Value"))
        self._start_process_btn.setText(_translate("LeafInterrogatorMainWindow", "Start Process"))
        self._editing_tabs.setTabText(self._editing_tabs.indexOf(self.processes_tab), _translate("LeafInterrogatorMainWindow", "Processes"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.edit_contour), _translate("LeafInterrogatorMainWindow", "Edit Contour"))
        self.groupBox_9.setTitle(_translate("LeafInterrogatorMainWindow", "Variance"))
        self.label_2.setText(_translate("LeafInterrogatorMainWindow", "X axis:"))
        self.label_4.setText(_translate("LeafInterrogatorMainWindow", "Y axis:"))
        self.label_3.setText(_translate("LeafInterrogatorMainWindow", "Total variance:"))
        self._y_percent_lbl.setText(_translate("LeafInterrogatorMainWindow", "0.0"))
        self._total_variance_lbl.setText(_translate("LeafInterrogatorMainWindow", "0.0"))
        self._x_percent_lbl.setText(_translate("LeafInterrogatorMainWindow", "0.0"))
        self._export_components_btn.setText(_translate("LeafInterrogatorMainWindow", "Export components"))
        self.x_axis_lbl.setText(_translate("LeafInterrogatorMainWindow", "X axis:"))
        self.y_axis_lbl.setText(_translate("LeafInterrogatorMainWindow", "Y axis:"))
        self._apply_shape_space_plot_conf_button.setText(_translate("LeafInterrogatorMainWindow", "Apply"))
        self._efd_size_invariant_checkbox.setText(_translate("LeafInterrogatorMainWindow", "Size invariant"))
        self._efd_normalize_checkbox.setText(_translate("LeafInterrogatorMainWindow", "Normalize"))
        self.label.setText(_translate("LeafInterrogatorMainWindow", "Method: "))
        self._harmonic_coeffs_groupbox.setTitle(_translate("LeafInterrogatorMainWindow", "Harmonic coefficients"))
        self._asymmetric_components_check_box.setText(_translate("LeafInterrogatorMainWindow", "Y axis symmetric: A, D components"))
        self._symmetric_components_check_box.setText(_translate("LeafInterrogatorMainWindow", "X axis symmetric: B, C components"))
        self._number_of_harmonics.setText(_translate("LeafInterrogatorMainWindow", "64"))
        self._number_of_harmonics_lbl.setText(_translate("LeafInterrogatorMainWindow", "Harmonics:"))
        self._method_combo_box.setItemText(0, _translate("LeafInterrogatorMainWindow", "Elliptical Fourier Descriptors"))
        self._tab_plot.setTabText(self._tab_plot.indexOf(self._tab_tweaks), _translate("LeafInterrogatorMainWindow", "Shape space"))
        self.groupBox_5.setTitle(_translate("LeafInterrogatorMainWindow", "Std. deviation"))
        self._number_of_std_lbl.setText(_translate("LeafInterrogatorMainWindow", "Ellipse scale:"))
        self._number_of_std.setText(_translate("LeafInterrogatorMainWindow", "1"))
        self._number_of_std_curves_lbl.setText(_translate("LeafInterrogatorMainWindow", "Ellipse number:"))
        self._number_of_std_curves.setText(_translate("LeafInterrogatorMainWindow", "1"))
        self._show_std_ellipse_check_box.setText(_translate("LeafInterrogatorMainWindow", "Std. Ellipse"))
        self._show_std_error_ellipse_check_box.setText(_translate("LeafInterrogatorMainWindow", "Std. Error"))
        self.groupBox_8.setTitle(_translate("LeafInterrogatorMainWindow", "Annotations"))
        self._shape_space_plot_background_image_zoom.setText(_translate("LeafInterrogatorMainWindow", "0.25"))
        self._shape_space_plot_show_back_ground_annotation_images_check_box.setToolTip(_translate("LeafInterrogatorMainWindow", "Show or hide background images."))
        self._shape_space_plot_show_back_ground_annotation_images_check_box.setText(_translate("LeafInterrogatorMainWindow", "Show BG Annotation images"))
        self._shape_space_plot_lim_lbl.setText(_translate("LeafInterrogatorMainWindow", "Plot lim increase (%):"))
        self._shape_space_plot_lim.setText(_translate("LeafInterrogatorMainWindow", "0"))
        self._shape_space_plot_background_number_of_rows_lbl.setText(_translate("LeafInterrogatorMainWindow", "No. rows:"))
        self._shape_space_plot_background_number_of_columns.setText(_translate("LeafInterrogatorMainWindow", "4"))
        self._shape_space_plot_background_number_of_columns_lbl.setText(_translate("LeafInterrogatorMainWindow", "No. Columns:"))
        self._shape_space_plot_background_number_of_rows.setText(_translate("LeafInterrogatorMainWindow", "3"))
        self._shape_space_plot_background_image_size_label.setText(_translate("LeafInterrogatorMainWindow", "BG image scale:"))
        self._shape_space_plot_point_size_lbl.setText(_translate("LeafInterrogatorMainWindow", "Points size:"))
        self._shape_space_plot_point_size.setText(_translate("LeafInterrogatorMainWindow", "10"))
        self.label_8.setText(_translate("LeafInterrogatorMainWindow", "BG image rotation:"))
        self._shape_space_plot_background_image_rotation.setText(_translate("LeafInterrogatorMainWindow", "180"))
        self._show_centroid_check_box.setText(_translate("LeafInterrogatorMainWindow", "Show centroids"))
        self._apply_plot_options_btn.setText(_translate("LeafInterrogatorMainWindow", "Apply To Plot"))
        self._tab_plot.setTabText(self._tab_plot.indexOf(self._tab_plot_options_3), _translate("LeafInterrogatorMainWindow", "Plot"))
        self._tab_plot.setTabText(self._tab_plot.indexOf(self._tab_colors_2), _translate("LeafInterrogatorMainWindow", "Colors"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.tab_shape_space), _translate("LeafInterrogatorMainWindow", "Shape Space"))
        self.menuFile.setTitle(_translate("LeafInterrogatorMainWindow", "File"))
        self.menuView.setTitle(_translate("LeafInterrogatorMainWindow", "View"))
        self.menuEdit.setTitle(_translate("LeafInterrogatorMainWindow", "Edit"))
        self.action_open.setText(_translate("LeafInterrogatorMainWindow", "Open File"))
        self.actionZoom_In.setText(_translate("LeafInterrogatorMainWindow", "Zoom in"))
        self.actionZoom_out.setText(_translate("LeafInterrogatorMainWindow", "Zoom out"))
        self.action_open_folder.setText(_translate("LeafInterrogatorMainWindow", "Open Folder"))
        self.action_save.setText(_translate("LeafInterrogatorMainWindow", "Save"))
        self.action_quit.setText(_translate("LeafInterrogatorMainWindow", "Quit"))
        self.actionRotate_Left.setText(_translate("LeafInterrogatorMainWindow", "Rotate Left"))
        self.actionRotate_Left.setShortcut(_translate("LeafInterrogatorMainWindow", "Ctrl+Left"))
        self.actionUndo.setText(_translate("LeafInterrogatorMainWindow", "Undo"))
        self.actionRedo.setText(_translate("LeafInterrogatorMainWindow", "Redo"))
        self.actionRotate_Right.setText(_translate("LeafInterrogatorMainWindow", "Rotate Right"))
        self.actionRotate_Right.setShortcut(_translate("LeafInterrogatorMainWindow", "Ctrl+Right"))
        self.actionReset_to_default.setText(_translate("LeafInterrogatorMainWindow", "Reset to default"))
        self.actionDelete.setText(_translate("LeafInterrogatorMainWindow", "Delete"))
        self.action_load_project.setText(_translate("LeafInterrogatorMainWindow", "Load project"))
        self.action_save_project.setText(_translate("LeafInterrogatorMainWindow", "Save project"))
        self.action_ocr.setText(_translate("LeafInterrogatorMainWindow", "OCR"))
        self.action_metadata_from_image_name.setText(_translate("LeafInterrogatorMainWindow", "Metadata from image name"))
        self.action_save_all.setText(_translate("LeafInterrogatorMainWindow", "Save All"))
        self.action_import_contours_csv_files.setText(_translate("LeafInterrogatorMainWindow", "Import contours (csv files)"))
from .contour_opengl_widget import ContourOpenGLWidget
from .edit_contour_opengl_widget import EditContourOpenGLWidget
from .image_opengl_widget import ImageOpenGLWidget
